name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/abystoma/external-workflow@branch
      - name: Greetings
        run: echo "$(<greetings.txt)"
